Fix stupid bug that caused Logger methods to be unreachable.
Current specification didn't catch this one, therefore split the spec in order to isolate logging tests. They silently hide the broken behavior because Logger methods (.warn, .error) are overriden in the spec. Error: TypeError: 'jasmine.FakeAjax.log.warn is not a function ...'

Splitted specification is more convenient also because now we get to see the real warnings/errors in firebug console while running.

Also clear context *before* each test, otherwise we may get 'TypeError: jasmine.FakeAjax.recordedSession is undefined' if context is not initialized in spec.